spring:
  datasource:
    url: jdbc:mysql://web-app-server.mysql.database.azure.com:3306/web-app-database
    username: 'iqandarghr'
    password: 'odeng00!1'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000