#spring:
#  jpa:
#    #전송 쿼리 확인
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#
#    #테이블 생성 후에 data.sql 실행
#    defer-datasource-initialization: true
# 구름톤 설정

 #UMC 설정
spring:
  datasource:
    url: univ-server.mysql.database.azure.com
    username: 'vcbpysauyz'
    password: 'ZJX8JJz8$OmBnaOe'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
jwt:
  issuer: ajufresh@gmail.com
  secret_key: ${JWT_SECRET}
  accessTokenExpiration: 3600000 #1시간
  #refreshTokenExpiration: 1209600000 #2주
kakao:
  client_id: ${KAKAO_API_KEY}
  redirect_uri: http://localhost:8080/callback
