# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - univ-test3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle #애저가 자동으로 생성한 스크립트는 maven을 사용 -> Gradle로 변경
        run: ./gradlew clean bootJar
      
      - name: Rename JAR to app.jar
        run: |
          JAR_PATH=$(find build/libs -name "*SNAPSHOT.jar" | grep -v "plain" | head -n 1)
          cp "$JAR_PATH" build/libs/app.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B6CC6574F2F7486E8B82AC846BE27666 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38A5A77A404A4451A7A2A680DA5D9CC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2194A574A0DE4F64B48B908BC20E735E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-app'
          slot-name: 'Production'
          package: 'app.jar'
          startup-command: 'java -jar /home/site/wwwroot/app.jar'
          
